//! L2 — JAX fixture smoke test for `convolve2d`.
//!
//! See `crates/flow-lenia-core/src/convolve.rs` module-level docs for the
//! L1+L2 testing strategy. Fixtures are generated by
//! `scripts/generate_jax_fixtures.py` and committed to
//! `tests/fixtures/`. CI does not need a JAX environment.
//!
//! Tolerance: relative `1e-3` per cell (with an absolute-error fallback for
//! cells whose expected value is near zero). Justification (DESIGN.md §4.5):
//! the only divergence between Rust direct correlation and JAX
//! `jax.scipy.signal.convolve2d` is internal addition / reduction order.

use flow_lenia_core::{config::BorderMode, convolve2d};
use ndarray::Array2;
use std::fs;
use std::path::PathBuf;

/// (`fixture stem`, `grid side`, `kernel side`, `border`).
/// Mirrors the `CASES` table in `scripts/generate_jax_fixtures.py` — if you
/// edit one, edit both.
const FIXTURES: &[(&str, usize, usize, BorderMode)] = &[
    ("case1_R5_r0.5_torus", 32, 21, BorderMode::Torus),
    ("case2_R10_r0.7_torus", 32, 37, BorderMode::Torus),
    ("case3_R5_r0.5_wall", 32, 21, BorderMode::Wall),
];

fn fixture_path(stem: &str, suffix: &str) -> PathBuf {
    // `CARGO_MANIFEST_DIR` for this integration test is the crate
    // (`crates/flow-lenia-core`); fixtures live at the workspace root.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join(format!("{stem}_{suffix}.bin"))
}

fn read_f32_bin(path: PathBuf, expected_len: usize) -> Vec<f32> {
    let bytes = fs::read(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {}: {e}", path.display()));
    assert_eq!(
        bytes.len(),
        expected_len * 4,
        "fixture {} has {} bytes, expected {}",
        path.display(),
        bytes.len(),
        expected_len * 4
    );
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

#[test]
fn jax_fixture_smoke() {
    let mut overall_max_abs = 0.0_f32;
    let mut overall_max_rel = 0.0_f32;
    let mut per_case_summary: Vec<String> = Vec::new();

    for &(stem, grid, ksize, border) in FIXTURES {
        let n = grid * grid;
        let kn = ksize * ksize;

        let a_vec = read_f32_bin(fixture_path(stem, "A"), n);
        let k_vec = read_f32_bin(fixture_path(stem, "K"), kn);
        let exp_vec = read_f32_bin(fixture_path(stem, "out"), n);

        let a = Array2::from_shape_vec((grid, grid), a_vec).unwrap();
        let k = Array2::from_shape_vec((ksize, ksize), k_vec).unwrap();
        let expected = Array2::from_shape_vec((grid, grid), exp_vec).unwrap();

        let got = convolve2d(&a, &k, border);

        let mut case_max_abs = 0.0_f32;
        let mut case_max_rel = 0.0_f32;
        for ((y, x), &got_v) in got.indexed_iter() {
            let exp_v = expected[[y, x]];
            let abs_err = (got_v - exp_v).abs();
            // Relative error guarded against tiny expected values.
            let rel_err = abs_err / exp_v.abs().max(1e-6);

            assert!(
                rel_err < 1e-3 || abs_err < 1e-6,
                "{stem} @ ({y}, {x}): expected {exp_v:e}, got {got_v:e}, \
                 abs_err = {abs_err:e}, rel_err = {rel_err:e}"
            );

            case_max_abs = case_max_abs.max(abs_err);
            case_max_rel = case_max_rel.max(rel_err);
        }
        overall_max_abs = overall_max_abs.max(case_max_abs);
        overall_max_rel = overall_max_rel.max(case_max_rel);

        per_case_summary.push(format!(
            "  {stem}: max_abs = {case_max_abs:.3e}, max_rel = {case_max_rel:.3e}"
        ));
    }

    // Surface the measured residuals via the test harness output (visible
    // with `cargo test -- --nocapture`).
    eprintln!("[L2 JAX fixture smoke] per-case errors:");
    for line in &per_case_summary {
        eprintln!("{line}");
    }
    eprintln!(
        "[L2 JAX fixture smoke] overall: max_abs = {overall_max_abs:.3e}, \
         max_rel = {overall_max_rel:.3e}"
    );
}
